; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	mathieucarbou/ESPAsyncWebServer@^3.6.0

; STREAMING_CHUNK:Correction du scanner de bibliotheques...
; Force PlatformIO a bien lier la librairie WiFi
lib_ldf_mode = deep+

; STREAMING_CHUNK:Activation du systeme de fichiers LittleFS...
; C'est cette ligne qui permet de stocker ton index.html en memoire flash
board_build.filesystem = littlefs

; STREAMING_CHUNK:Activation de la memoire externe...
; Indispensable pour traiter le flux video (PSRAM)
build_flags =
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
